<?php
/** @var $block \Prince\Faq\Block\Index\Index */
$faqGroupCollection = $block->getFaqGroupCollection();
$faqCollection = $block->getFaqCollection($block->getGroupId());
$group = $block->getGroupById($block->getGroupId());
?>
<?php if ($block->isShowGroupTitle()) : ?>
    <div class="group-title" id="group<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>">
        <i></i><?php /* @noEscape */ echo $group->getGroupName(); ?>
    </div>
<?php endif; ?>
<div class="faq-accordion">
    <?php $faqCollection = $block->getFaqCollection($group->getId()); ?>
    <?php if ($faqCollection->getSize()) : ?>
        <?php foreach ($faqCollection as $faq) : ?>
            <h3><?php /* @noEscape */ echo $faq->getTitle(); ?></h3>
            <div>
                <p><?php /* @noEscape */ echo $block->filterOutputHtml($faq->getContent()); ?></p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
